steps:
  # 其他步驟...
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bable'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bable'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,FIREBASE_API_KEY=${_FIREBASE_API_KEY},FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN},FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID},FIREBASE_APP_ID=${_FIREBASE_APP_ID}' 